// import type { Metadata } from "next";
'use client'
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar"
import { HospitalSidebar } from "@/components/custom/ui/SideBar"
import { Header } from "@/components/custom/ui/header"
import { Toaster } from "@/components/ui/toaster";
import { usePathname } from "next/navigation";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { DocotorsProvider, PatientsProvider } from "./provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const excludePaths = ["/auth/login"]
  const pathname = usePathname()
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased scrollbar-thin w-full`}>
        <QueryClientProvider client={new QueryClient}>
          <PatientsProvider>
            <DocotorsProvider>
              {
                pathname && !excludePaths.includes(pathname) ? <SidebarProvider>
                  <div className="flex h-screen overflow-hidden w-full">
                    <HospitalSidebar />
                    <div className="flex w-full flex-col flex-1 overflow-hidden">
                      <Header />
                      <main className="flex-1 scrollbar-thin overflow-y-auto bg-background p-8">
                        {children}
                      </main>
                    </div>
                  </div>
                </SidebarProvider> : <main className="flex-1 overflow-y-auto bg-background p-8">
                  {children}
                </main>
              }

              <Toaster />
            </DocotorsProvider>
          </PatientsProvider>
        </QueryClientProvider>
      </body>
    </html>

  );
}
